"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Check, CircleHelp, Download, FileText, Headphones, Pencil, Printer, RefreshCw, Save, Sparkles, Volume2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { sampleNotes, samples } from "@/lib/studymate/demo";
import type { Lecture, Student } from "@/lib/studymate/types";
import { formatDuration, moveLecture, newId } from "@/lib/studymate/types";
import { readAudio } from "@/lib/studymate/storage";
import { generateStudy, speakEnglish } from "@/lib/studymate/ai-client";
import { Blank, Download as TextDownload, Picker } from "./common";

export function LectureDetail({ lecture, student, aiReady, onChange, onBack }: { lecture: Lecture; student: Student; aiReady: boolean; onChange: (l: Lecture) => boolean; onBack: () => void }) {
 const [tab, setTab] = useState("summary");
 const [year, setYear] = useState(lecture.notesYear || student.year);
 const [busy, setBusy] = useState(false);
 const [audioUrl, setAudioUrl] = useState("");
 const [audioType, setAudioType] = useState("");
 const [term, setTerm] = useState<number | null>(null);
 const [editing, setEditing] = useState(false);
 const [overview, setOverview] = useState(lecture.notes?.overview ?? "");
 const [takeaways, setTakeaways] = useState(lecture.notes?.takeaways.join("\n") ?? "");
 const [transcript, setTranscript] = useState(lecture.segments.map(s => s.korean).join("\n\n"));
 const [editTranscript, setEditTranscript] = useState(false);
 const [suggested, setSuggested] = useState<string | null | undefined>(undefined);
 const [newTitle, setNewTitle] = useState(lecture.title);
 useEffect(() => {
  let disposed = false; let url = "";
  if (lecture.hasAudio) readAudio(lecture.id).then(blob => { if (!blob) { toast.error("This browser no longer has the audio file. Your text notes are still available."); return; } if (!disposed) { url = URL.createObjectURL(blob); setAudioUrl(url); setAudioType(blob.type); } }).catch(e => toast.error(e.message));
  return () => { disposed = true; if (url) URL.revokeObjectURL(url); if ("speechSynthesis" in window) speechSynthesis.cancel(); };
 }, [lecture.id, lecture.hasAudio]);
 const subject = student.subjects.find(s => s.id === lecture.subjectId);
 const quiz = lecture.notes?.questions ?? [];
 const answered = Object.keys(lecture.quizAnswers).length;
 const correct = quiz.filter((q, i) => lecture.quizAnswers[i] === q.answer).length;
 const sample = samples.find(s => s.id === lecture.sampleId);
 const sampleComplete = !!sample && lecture.segments.length === sample.segments.length;
 async function generate() {
  if (!lecture.segments.some(s => s.korean.trim())) { toast.error("Add a Korean transcript first."); setTab("transcript"); return; }
  if (lecture.mode === "sample" && !sampleComplete) { toast.error("This sample was stopped early. Play the full sample to use its prepared study notes."); return; }
  setBusy(true);
  try {
   if (lecture.mode === "sample" && sample) { onChange({ ...lecture, notes: sampleNotes(sample, year), notesYear: year, quizAnswers: {} }); }
   else {
    const result = await generateStudy(lecture.segments, student, year);
    const ok = onChange({ ...lecture, title: result.title || lecture.title, segments: lecture.segments.map(s => ({ ...s, english: result.translations.find(t => t.id === s.id)?.english ?? s.english })), notes: result.notes, notesYear: year, quizAnswers: {} });
    if (ok) { setSuggested(result.subjectId); setNewTitle(result.title || lecture.title); }
   }
  } catch (e) { toast.error(e instanceof Error ? e.message : "Study notes could not be generated."); } finally { setBusy(false); }
 }
 function changeSubject(value: string) { try { if (onChange(moveLecture(lecture, value === "unfiled" ? null : value, student))) toast.success("Lecture folder updated."); } catch (e) { toast.error((e as Error).message); } }
 const plainNotes = [lecture.title, subject?.name ?? "Unfiled", "Summary level: Year " + lecture.notesYear, lecture.notes?.overview ?? "", ...(lecture.notes?.takeaways.map(t => "• " + t) ?? []), "", "KOREAN TRANSCRIPT / ENGLISH TRANSLATION", ...lecture.segments.map(s => "[" + formatDuration(s.seconds) + "]\n" + s.korean + "\n" + s.english)].join("\n\n");
 return <><Button variant="ghost" className="back-link no-print" onClick={onBack}><ArrowLeft size={16} />{subject?.name ?? "All subjects"}</Button><div className="page-heading lecture-heading"><div><p className="eyebrow">{lecture.mode === "sample" ? "SAMPLE LECTURE · PREPARED STUDY MATERIALS" : "SAVED LECTURE"}</p><h1>{lecture.title}</h1><p>{new Date(lecture.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}<span className="text-separator">·</span>{formatDuration(lecture.duration)}<span className="text-separator">·</span>Year {lecture.notesYear}</p></div><div className="lecture-export no-print"><Button variant="outline" onClick={() => window.print()}><Printer size={17} />Print / save PDF</Button><TextDownload text={plainNotes} name="studymate-lecture.txt"><Download size={17} /><span className="sr-only">Download text</span></TextDownload></div></div><div className="lecture-organise no-print"><label className="grow">Subject folder<Picker label="Subject folder" value={lecture.subjectId ?? "unfiled"} onChange={changeSubject} options={[{ value: "unfiled", label: "Unfiled" }, ...student.subjects.map(s => ({ value: s.id, label: s.name }))]} /></label><label className="grow">Lecture title<Input value={newTitle} maxLength={150} onChange={e => setNewTitle(e.target.value)} /></label><Button variant="outline" disabled={!newTitle.trim() || newTitle === lecture.title} onClick={() => { if (onChange({ ...lecture, title: newTitle.trim() })) toast.success("Title saved."); }}><Save size={17} />Save title</Button></div>{suggested !== undefined && <div className="notice suggestion no-print"><Sparkles size={18} /><div><strong>{suggested ? "Suggested subject: " + (student.subjects.find(s => s.id === suggested)?.name ?? "Unknown") : "No clear subject match"}</strong><p>{suggested ? "Confirm this suggestion or choose another subject above." : "Choose the subject folder yourself. Your lecture is already saved."}</p></div>{suggested && <Button size="sm" onClick={() => { changeSubject(suggested); setSuggested(undefined); }}>Use this subject</Button>}<Button variant="ghost" size="icon" aria-label="Dismiss subject suggestion" onClick={() => setSuggested(undefined)}><X size={16} /></Button></div>}{audioUrl && <div className="saved-audio"><Headphones size={22} /><span>Original recording</span><audio controls src={audioUrl} /><a href={audioUrl} download={"studymate-recording." + (audioType.includes("mp4") ? "m4a" : "webm")}>Download</a></div>}
 <Tabs value={tab} onValueChange={setTab} className="lecture-tabs"><TabsList className="lecture-tab-list no-print"><TabsTrigger value="summary"><Sparkles size={16} />Study notes</TabsTrigger><TabsTrigger value="transcript"><FileText size={16} />Transcript</TabsTrigger><TabsTrigger value="quiz"><CircleHelp size={16} />Review quiz</TabsTrigger></TabsList><TabsContent value="summary"><div className="notes-layout"><section className="panel summary-panel"><div className="section-heading compact"><h2>The big picture</h2>{lecture.notes && <Button variant="ghost" size="sm" className="no-print" onClick={() => { setOverview(lecture.notes!.overview); setTakeaways(lecture.notes!.takeaways.join("\n")); setEditing(true); }}><Pencil size={15} />Edit</Button>}</div>{lecture.notes ? <><p className="overview-text">{lecture.notes.overview}</p><h3 className="takeaways-heading">What to remember</h3><ol className="takeaway-list">{lecture.notes.takeaways.map((t, i) => <li key={i}><span>{String(i + 1).padStart(2, "0")}</span><p>{t}</p></li>)}</ol></> : <Blank title="Turn this lecture into study notes" description={lecture.mode === "sample" ? "Complete sample playback includes prepared notes and a quiz." : aiReady ? "Generate an English summary, key terms, and a short review quiz from your transcript." : "Your recording is saved. Connect live AI to generate notes, or explore the sample lecture."} />}</section><aside className="notes-aside"><section className="panel level-panel"><GraduationIcon /><h3>At your level</h3><p>Choose how much background the explanation assumes.</p><Picker label="Summary academic year" value={String(year)} onChange={v => setYear(Number(v))} options={[1, 2, 3, 4, 5, 6].map(y => ({ value: String(y), label: "Year " + y }))} /><Button onClick={generate} disabled={busy || lecture.mode === "recording" && !aiReady || lecture.mode === "sample" && !sampleComplete}><RefreshCw size={16} className={busy ? "spin" : ""} />{busy ? "Preparing notes…" : lecture.notes ? "Update study notes" : "Generate study notes"}</Button><small>{lecture.mode === "sample" ? "Sample notes use two prepared levels: Years 1–2 and Years 3–6." : aiReady ? "Uses the saved Korean transcript. AI can make mistakes; check important details." : "Live AI is not connected yet."}</small></section>{lecture.notes && <section className="panel key-terms"><h3>Key terms</h3><p>Tap a term to unpack its meaning.</p>{lecture.notes.terms.map((t, i) => <button key={i} onClick={() => setTerm(i)}><span><strong>{t.term}</strong><small lang="ko">{t.korean}</small></span><CircleHelp size={17} /></button>)}</section>}</aside></div></TabsContent>
 <TabsContent value="transcript"><section className="panel"><div className="section-heading compact"><h2>Original words, clearer meaning</h2><div className="capture-actions"><Button variant="outline" onClick={() => { const text = lecture.segments.map(s => s.english).filter(Boolean).join(" "); if (!text) { toast.error("No English translation is available yet."); return; } if ("speechSynthesis" in window) speechSynthesis.cancel(); if (!speakEnglish(text)) toast.error("Spoken playback is not available in this browser."); }}><Volume2 size={17} />Listen in English</Button><Button variant="ghost" onClick={() => { if ("speechSynthesis" in window) speechSynthesis.cancel(); }}>Stop</Button>{lecture.mode !== "sample" && <Button variant="outline" onClick={() => { setTranscript(lecture.segments.map(s => s.korean).join("\n\n")); setEditTranscript(true); }}><Pencil size={16} />{lecture.segments.length ? "Edit transcript" : "Add transcript"}</Button>}</div></div>{lecture.segments.length ? <div className="saved-transcript">{lecture.segments.map(s => <div className="saved-segment" key={s.id}><time>{formatDuration(s.seconds)}</time><p lang="ko">{s.korean}</p><p>{s.english || "English translation is not available yet."}</p></div>)}</div> : <Blank title="No transcript yet" description="Your browser may not support Korean speech recognition. Paste a Korean transcript to continue." />}</section></TabsContent>
 <TabsContent value="quiz">{quiz.length ? <section className="panel quiz-panel"><div className="section-heading compact"><div><h2>A quick check-in</h2><p className="muted">Answer from memory, then review the explanation.</p></div><span className="tag">{answered}/{quiz.length} answered</span></div>{quiz.map((q, i) => { const selected = lecture.quizAnswers[i]; return <article className="quiz-question" key={i}><p className="eyebrow">QUESTION {i + 1}</p><h3>{q.question}</h3><RadioGroup value={selected === undefined ? "" : String(selected)} onValueChange={v => onChange({ ...lecture, quizAnswers: { ...lecture.quizAnswers, [i]: Number(v) } })} disabled={selected !== undefined} aria-label={q.question}>{q.options.map((option, j) => <label className={"quiz-option " + (selected === undefined ? "" : j === q.answer ? "correct" : j === selected ? "incorrect" : "")} key={j}><RadioGroupItem value={String(j)} id={"q" + i + "o" + j} /><span>{option}</span></label>)}</RadioGroup>{selected !== undefined && <div className={"quiz-feedback " + (selected === q.answer ? "correct" : "incorrect")}><strong>{selected === q.answer ? "Correct" : "Not quite"}</strong><p>{q.explanation}</p></div>}</article>; })}{answered === quiz.length && <div className="quiz-result"><Check size={23} /><strong>{correct} of {quiz.length} correct</strong><Button variant="outline" onClick={() => onChange({ ...lecture, quizAnswers: {} })}>Try again</Button></div>}</section> : <Blank title="Your quiz will appear here" description="Generate study notes first. Review questions are based on the lecture transcript." action="Study notes" onAction={() => setTab("summary")} />}</TabsContent></Tabs>
 <Dialog open={term !== null} onOpenChange={v => !v && setTerm(null)}><DialogContent><DialogHeader><DialogTitle>{lecture.notes?.terms[term ?? 0]?.term}</DialogTitle><DialogDescription lang="ko">{lecture.notes?.terms[term ?? 0]?.korean}</DialogDescription></DialogHeader><p className="term-explanation">{lecture.notes?.terms[term ?? 0]?.explanation}</p><span className="tag">Explanation for Year {lecture.notesYear}</span></DialogContent></Dialog>
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent><DialogHeader><DialogTitle>Edit your study notes</DialogTitle><DialogDescription>Your edits are saved with this lecture.</DialogDescription></DialogHeader><label>Overview<Textarea rows={5} value={overview} maxLength={8000} onChange={e => setOverview(e.target.value)} /></label><label>Takeaways — one per line<Textarea rows={7} value={takeaways} maxLength={12000} onChange={e => setTakeaways(e.target.value)} /></label><Button onClick={() => { if (!overview.trim()) { toast.error("Add a summary before saving."); return; } if (lecture.notes && onChange({ ...lecture, notes: { ...lecture.notes, overview: overview.trim(), takeaways: takeaways.split("\n").map(t => t.trim()).filter(Boolean) } })) setEditing(false); }}>Save notes</Button></DialogContent></Dialog>
 <Dialog open={editTranscript} onOpenChange={setEditTranscript}><DialogContent><DialogHeader><DialogTitle>Korean transcript</DialogTitle><DialogDescription>Changing the transcript clears old translations, study notes, and quiz answers so they can be generated again. The audio recording stays saved.</DialogDescription></DialogHeader><Textarea lang="ko" aria-label="Korean transcript text" rows={12} value={transcript} maxLength={45000} onChange={e => setTranscript(e.target.value)} /><Button onClick={() => { if (!transcript.trim()) { toast.error("Enter a transcript first."); return; } const entries = transcript.split(/\n\s*\n/).map(t => t.trim()).filter(Boolean); if (entries.length > 200) { toast.error("Use at most 200 paragraphs for this prototype."); return; } if (onChange({ ...lecture, segments: entries.map(korean => ({ id: newId(), seconds: 0, korean, english: "" })), notes: null, quizAnswers: {} })) { setEditTranscript(false); toast.success("Transcript saved. Generate study notes to translate it."); } }}>Save transcript</Button></DialogContent></Dialog></>;
}
function GraduationIcon() { return <span className="subject-icon blue"><Sparkles size={22} /></span>; }
